# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/verymoe"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://x.com/verymoes"
    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "telegram"
    name       = "Telegram"
    url        = "https://t.me/verymoes"
    [social.params]
        icon = "brand-telegram"

[[social]]
    identifier = "matrix"
    name       = "Matrix"
    url        = "https://matrix.to/#/@lolicon:mozilla.org"
    [social.params]
    icon = "brand-matrix"
