# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/verymoe"
    weight     = 1
    [social.params]
        icon = "brand-github"
        newtab = true

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://x.com/verymoes"
    weight     = 2
    [social.params]
        icon = "brand-twitter"
        newtab = true

[[social]]
    identifier = "telegram"
    name       = "Telegram"
    url        = "https://t.me/verymoes"
    weight     = 3
    [social.params]
        icon = "brand-telegram"
        newtab = true

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:shiro@332.email"
    weight     = 4
    [social.params]
        icon = "mail"
        newtab = true

[[social]]
    identifier = "matrix"
    name       = "Matrix"
    url        = "https://matrix.to/#/@lolicon:mozilla.org"
    weight     = 5
    [social.params]
        icon = "brand-matrix"
        newtab = true
